//! Crate-level `forge suggest run`: one bounded local adapter invocation.
//!
//! The run is the only step that touches a model, and it is local by
//! construction: the payload was frozen by `prepare`, the consent token must
//! authorise exactly that payload and adapter, and the adapter is an operator
//! executable invoked with a cleared environment. Nothing is generated by FORGE
//! and nothing is sent anywhere.

use std::path::Path;

use crate::ForgeError;
use crate::cli::AuthorReportFormat;

use super::adapter::{LocalModelInvoke, ProcessModelAdapter, RecordedResponseAdapter};
use super::consent::ConsentToken;
use super::request::SuggestRequest;
use super::run_record::{RunMode, RunRecord, SCHEMA_VERSION as RUN_SCHEMA_VERSION};
use super::shared;

/// Artifact name of the raw adapter response.
pub const RESPONSE_ARTIFACT: &str = "response.raw";
/// Artifact name of the run record.
pub const RUN_RECORD_ARTIFACT: &str = "run.json";
/// Default adapter timeout in seconds.
pub const DEFAULT_TIMEOUT_SECS: u64 = 60;
/// Maximum adapter timeout in seconds.
pub const MAX_TIMEOUT_SECS: u64 = 3_600;

/// Arguments for one run.
pub struct RunArgs<'a> {
    /// The prepared request document.
    pub request: &'a Path,
    /// The consent token authorising this exact payload.
    pub consent: &'a Path,
    /// New directory beneath the request's directory.
    pub output_dir: &'a Path,
    /// Adapter executable override; its digest must match the request.
    pub adapter: Option<&'a Path>,
    /// Adapter timeout in seconds.
    pub timeout_secs: u64,
    /// Replay a recorded response instead of invoking a process.
    pub recorded_response: Option<&'a Path>,
    /// Stdout format.
    pub format: AuthorReportFormat,
}

/// Invoke the local adapter once and publish the bounded response.
///
/// Returns `true` when a valid request could not be completed by the
/// environment (a missing, failing or over-bound adapter), which the CLI maps
/// to the action-required exit code.
///
/// # Errors
/// Returns an authoring error for an invalid argument, a contract violation, a
/// consent that does not authorise the request, a payload that changed after
/// consent, or publication failure.
pub fn execute(args: &RunArgs<'_>) -> Result<bool, ForgeError> {
    if args.timeout_secs == 0 || args.timeout_secs > MAX_TIMEOUT_SECS {
        return Err(shared::error(format!(
            "--timeout must be between 1 and {MAX_TIMEOUT_SECS} seconds"
        )));
    }
    let request_bytes = crate::io::read_bounded(args.request, super::request::MAX_REQUEST_BYTES)?;
    let request = SuggestRequest::parse(&request_bytes)?;
    let consent = ConsentToken::parse(&crate::io::read_bounded(
        args.consent,
        super::consent::MAX_CONSENT_BYTES,
    )?)?;
    consent.authorises(&request)?;

    let root = args
        .request
        .parent()
        .map(std::fs::canonicalize)
        .transpose()
        .map_err(|cause| shared::error(format!("cannot resolve the request directory: {cause}")))?
        .ok_or_else(|| shared::error("--request must name a file in a directory"))?;
    let payload_path = root.join(&request.payload.artifact);
    let payload = crate::io::read_bounded(&payload_path, super::request::MAX_PAYLOAD_BYTES)?;
    if crate::hashing::sha256_hex(&payload) != request.payload.sha256
        || payload.len() as u64 != request.payload.bytes
    {
        return Err(shared::error(
            "the payload changed after consent; re-run prepare and consent again",
        ));
    }

    let timeout = std::time::Duration::from_secs(args.timeout_secs);
    let (adapter, mode): (Box<dyn LocalModelInvoke>, RunMode) = if let Some(recorded) =
        args.recorded_response
    {
        (Box::new(RecordedResponseAdapter::new(recorded)?), RunMode::RecordedResponse)
    } else {
        let executable = args.adapter.unwrap_or_else(|| Path::new(&request.adapter.executable));
        let process = ProcessModelAdapter::new(executable, &request.adapter.argv)?;
        if process.executable_sha256() != Some(request.adapter.executable_sha256.as_str()) {
            return Err(shared::error(
                "the adapter executable changed since consent; re-run prepare and consent again",
            ));
        }
        (Box::new(process), RunMode::Process)
    };

    let output = match adapter.invoke(&payload, timeout) {
        Ok(output) => output,
        Err(cause) => {
            // The request and consent were valid; the local environment could
            // not complete the run, so this is action-required, not invalid input.
            crate::cli::output::write_output(&format!("run refused: {cause}\n"), None)
                .map_err(|error| shared::error(format!("cannot write the run summary: {error}")))?;
            return Ok(true);
        }
    };
    let response_sha256 = crate::hashing::sha256_hex(&output.stdout);
    let record = RunRecord {
        schema_version: RUN_SCHEMA_VERSION.to_string(),
        request_sha256: crate::hashing::sha256_hex(&request_bytes),
        payload_sha256: request.payload.sha256.clone(),
        response_sha256,
        response_bytes: u64::try_from(output.stdout.len())
            .map_err(|_| shared::error("response length does not fit the contract"))?,
        response_artifact: RESPONSE_ARTIFACT.to_string(),
        adapter_executable_sha256: request.adapter.executable_sha256.clone(),
        model_id: request.adapter.model_id.clone(),
        argv: request.adapter.argv.clone(),
        redactions: request.redactions.clone(),
        elapsed_ms: u64::try_from(output.elapsed.as_millis()).unwrap_or(u64::MAX),
        exit_code: output.exit_code.unwrap_or(0),
        mode,
    };
    let record_json = serde_json::to_vec_pretty(&record)
        .map_err(|cause| shared::error(format!("cannot encode the run record: {cause}")))?;
    RunRecord::parse(&record_json)?;

    let artifacts = vec![
        crate::authoring::output::OutputArtifact {
            relative_path: RESPONSE_ARTIFACT.to_string(),
            bytes: output.stdout.clone(),
        },
        crate::authoring::output::OutputArtifact {
            relative_path: RUN_RECORD_ARTIFACT.to_string(),
            bytes: record_json.clone(),
        },
    ];
    crate::authoring::output::publish(&root, args.output_dir, &artifacts)?;

    let stdout = match args.format {
        AuthorReportFormat::Json => String::from_utf8(record_json)
            .map_err(|cause| shared::error(format!("run record JSON encoding: {cause}")))?,
        AuthorReportFormat::Text => render_summary(&record, args),
    };
    crate::cli::output::write_output(&stdout, None)
        .map_err(|cause| shared::error(format!("cannot write the run summary: {cause}")))?;
    if output.stderr.trim().is_empty() {
        return Ok(false);
    }
    crate::cli::output::write_output(&format!("adapter stderr: {}\n", output.stderr.trim()), None)
        .map_err(|cause| shared::error(format!("cannot write the adapter diagnostics: {cause}")))?;
    Ok(false)
}

/// The text summary for one run.
fn render_summary(record: &RunRecord, args: &RunArgs<'_>) -> String {
    use std::fmt::Write as _;
    let mut summary = String::new();
    let _ = writeln!(summary, "ran {} adapter", record.mode.as_str());
    let _ = writeln!(summary, "model: {}", record.model_id);
    let _ = writeln!(
        summary,
        "response bytes: {} sha256: {}",
        record.response_bytes, record.response_sha256
    );
    let _ = writeln!(summary, "elapsed: {} ms", record.elapsed_ms);
    let _ = writeln!(summary, "output: {}", args.output_dir.display());
    let _ = writeln!(summary, "next: forge suggest validate --request ... --run ...");
    summary
}
